#!/usr/bin/env python3
"""
Bloodbank consumer for hermes agent {{agent_id}}.

Subscribes to:
    bloodbank.evt.v1.repo.>
    bloodbank.cmd.v1.agent.>

The Bloodbank subject identifies the fixed domain/entity/action route. Repo and
agent identifiers stay in envelope data, so this consumer filters repo events
by ``data.repo`` and agent commands by ``data.target_agent_id``.

For each event/command received, writes it to the agent's notification queue at
$HERMES_HOME/bloodbank-inbox/<timestamp>.json so the gateway can ingest it on
the next tick. Reconnects on broker churn; idempotent across restarts.

Generated by hermes-agent-template/runtime-scaffold/bloodbank-consumer.py and
rendered with role-specific values at provision time. Re-render by re-running
agents/hermes/{{role}}/.scripts/20-runtime-repo.sh — do NOT edit by hand.
"""

import asyncio
import json
import os
import pathlib
import signal
import sys
import time
import uuid
from datetime import datetime, timezone

try:
    import nats
except ImportError:
    sys.stderr.write("nats-py not installed. install with: pip install nats-py\n")
    sys.exit(2)


HERMES_HOME = pathlib.Path(os.environ.get("HERMES_HOME", str(pathlib.Path.home() / ".hermes")))
INBOX_DIR = HERMES_HOME / "bloodbank-inbox"
INBOX_DIR.mkdir(parents=True, exist_ok=True)

NATS_HOST = os.environ.get("BLOODBANK_NATS_HOST", "127.0.0.1")
NATS_PORT = int(os.environ.get("BLOODBANK_NATS_PORT", "4222"))
NATS_URL = f"nats://{NATS_HOST}:{NATS_PORT}"

AGENT_ID = "{{agent_id}}"
REPO     = "{{repo}}"
ROLE     = "{{role}}"
PRODUCER = f"hermes-agent:{AGENT_ID}"
SOURCE   = f"hermes://agent/{AGENT_ID}"

SUBJECTS = [
    "bloodbank.evt.v1.repo.>",
    "bloodbank.cmd.v1.agent.>",
]

KIND_MARKERS = {"event": "evt", "command": "cmd", "reply": "rpy"}


def _now():
    return datetime.now(timezone.utc).isoformat()


def _subject_and_domain(ce_type, kind):
    parts = ce_type.split(".")
    if len(parts) != 5 or parts[0] != "bloodbank" or parts[1] != "v1":
        raise ValueError(f"type {ce_type!r} must match bloodbank.v1.<domain>.<entity>.<action>")
    if kind not in KIND_MARKERS:
        raise ValueError(f"unknown envelope kind {kind!r}")
    _vendor, version, domain, entity, action = parts
    return f"bloodbank.{KIND_MARKERS[kind]}.{version}.{domain}.{entity}.{action}", domain


def build_envelope(ce_type, data, *, kind="event", correlationid=None, causationid=None):
    """Mirror of bloodbank/services/agent-hooks/core/envelope.build_envelope."""
    subject, domain = _subject_and_domain(ce_type, kind)
    env = {
        "specversion": "1.0",
        "type": ce_type,
        "id": str(uuid.uuid4()),
        "source": SOURCE,
        "subject": subject,
        "time": _now(),
        "datacontenttype": "application/json",
        "kind": kind,
        "producer": PRODUCER,
        "service": "hermes-agent",
        "domain": domain,
        "actor": {"type": "agent", "agent_id": AGENT_ID, "cli": "hermes"},
        "data": data,
        "correlationid": correlationid or str(uuid.uuid4()),
        "causationid": causationid or str(uuid.uuid4()),
    }
    if kind == "event":
        env["ordering_key"] = f"agent:{AGENT_ID}"
    return env


def _is_for_consumer(subject, payload):
    """Route canonical subjects using identifiers carried in envelope data."""
    if not isinstance(payload, dict):
        return False
    parts = subject.split(".")
    if len(parts) != 6 or parts[0] != "bloodbank" or parts[2] != "v1":
        return False

    _vendor, kind, version, domain, entity, action = parts
    if kind not in KIND_MARKERS.values():
        return False
    if KIND_MARKERS.get(payload.get("kind")) != kind:
        return False
    if payload.get("subject") != subject:
        return False
    if payload.get("type") != f"bloodbank.{version}.{domain}.{entity}.{action}":
        return False
    data = payload.get("data")
    if not isinstance(data, dict):
        return False
    if kind == "evt" and domain == "repo":
        return data.get("repo") == REPO
    if kind == "cmd" and domain == "agent":
        return data.get("target_agent_id") == AGENT_ID
    return False


async def main():
    nc = await nats.connect(NATS_URL, name=f"hermes-{AGENT_ID}")
    stop = asyncio.Event()

    async def on_msg(msg):
        try:
            payload = json.loads(msg.data.decode())
        except Exception:
            sys.stderr.write(f"[bloodbank-consumer:{AGENT_ID}] skipped unroutable payload on {msg.subject}\n")
            return
        if not _is_for_consumer(msg.subject, payload):
            return
        entry = {
            "received_at": _now(),
            "subject": msg.subject,
            "reply_to": msg.reply,
            "payload": payload,
        }
        fname = f"{int(time.time()*1000):013d}-{uuid.uuid4().hex[:8]}.json"
        tmp = INBOX_DIR / (fname + ".tmp")
        tmp.write_text(json.dumps(entry, indent=2))
        tmp.rename(INBOX_DIR / fname)
        sys.stderr.write(f"[bloodbank-consumer:{AGENT_ID}] {msg.subject} -> {fname}\n")

    for subj in SUBJECTS:
        await nc.subscribe(subj, cb=on_msg)
        sys.stderr.write(f"[bloodbank-consumer:{AGENT_ID}] subscribed: {subj}\n")

    # Announce presence
    online = build_envelope(
        "bloodbank.v1.agent.online.changed",
        {"agent_id": AGENT_ID, "repo": REPO, "role": ROLE, "state": "online"},
    )
    await nc.publish(online["subject"], json.dumps(online).encode())

    def _shutdown(*_):
        stop.set()
    signal.signal(signal.SIGTERM, _shutdown)
    signal.signal(signal.SIGINT, _shutdown)

    await stop.wait()

    offline = build_envelope(
        "bloodbank.v1.agent.online.changed",
        {"agent_id": AGENT_ID, "repo": REPO, "role": ROLE, "state": "offline"},
    )
    await nc.publish(offline["subject"], json.dumps(offline).encode())
    await nc.drain()


if __name__ == "__main__":
    try:
        asyncio.run(main())
    except KeyboardInterrupt:
        pass
